// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptejgjxrbnoqraduvpog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZWpnanhyYm5vcXJhZHV2cG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzgxOTEsImV4cCI6MjA2ODI1NDE5MX0.N-vWN0uMF9hd8SajW2Cm_NKUC5USKoR04zsSyWn7mzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});